/**
 * Promoter sessions, fighter invite tokens, and the renderer's key.
 *
 * There is no third-party auth here on purpose. The whole product has exactly
 * three kinds of caller — one promoter who owns a show, a fighter who was sent
 * a link, and the mp4 renderer, which is a machine holding a shared key — and
 * none of them justifies an identity provider, a redirect dance or a dependency
 * that has to be kept current. Web Crypto is in the Workers runtime and in
 * Node, so the same code runs in tests, in `next dev` and on the edge.
 *
 * The promoter's session is a signed cookie rather than a row in the database:
 * a signature can be checked without a read, and there is no session state worth
 * storing. Logging out clears the cookie; there is deliberately no server-side
 * revocation, because with one operator it would be ceremony rather than
 * security. Sessions expire, and the expiry is inside the signed payload so it
 * cannot be edited by the holder.
 */

const encoder = new TextEncoder();

/** Long enough that a promoter is not logged out mid-show, short enough to matter. */
export const SESSION_MAX_AGE_SECONDS = 60 * 60 * 24 * 14;

export const SESSION_COOKIE = "eventiq_session";

/**
 * A ceiling imposed by the runtime, not a number anybody chose. The deployed
 * Workers runtime refuses PBKDF2 above 100,000 iterations outright, so OWASP's
 * floor for PBKDF2-SHA256 — six times higher — simply cannot be reached here.
 *
 * The trap is that this is invisible everywhere it would be caught. Node has no
 * cap, so the tests and `next dev` pass at any count, and so does the local
 * `wrangler dev`, because the open-source workerd build does not enforce it
 * either. Only the real edge does, and it does so exactly at 100,000: a probe
 * run through `wrangler dev --remote` derives at 100,000 and throws
 * `NotSupportedError: Pbkdf2 failed: iteration counts above 100000 are not
 * supported` at 100,001. So a hash minted at 600,000 by the seed script looks
 * healthy through every local check and then locks the promoter out of the live
 * site on their first sign-in.
 *
 * Verification reads the count out of the stored hash, so lowering this does not
 * invalidate hashes already written below the cap — but any hash written above
 * it is unverifiable in production and has to be regenerated by re-seeding.
 */
const PBKDF2_ITERATIONS = 100_000;

/**
 * A well-formed hash that no password matches, for the login to spend its time
 * on when the promoter does not exist.
 *
 * Built from the constant above rather than written out, because when it was
 * written out the two drifted: the constant came down to the runtime's cap and
 * this literal stayed at 600,000, so signing in as an unknown promoter kept
 * throwing on the edge long after the real login was fixed.
 */
export const ABSENT_PROMOTER_HASH =
  `${PBKDF2_ITERATIONS}:AAAAAAAAAAAAAAAAAAAAAA:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA` as const;

function toBase64Url(bytes: Uint8Array): string {
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

function fromBase64Url(value: string): Uint8Array {
  const padded = value.replace(/-/g, "+").replace(/_/g, "/");
  const binary = atob(padded + "=".repeat((4 - (padded.length % 4)) % 4));
  return Uint8Array.from(binary, (char) => char.charCodeAt(0));
}

/**
 * Constant time within the limits of the runtime. The comparison never returns
 * early, so the time it takes does not depend on how much of a forged signature
 * happened to be right.
 */
function equal(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i += 1) diff |= a[i] ^ b[i];
  return diff === 0;
}

/**
 * The header the mp4 renderer presents instead of a cookie. Kept out of the
 * `authorization` header on purpose: this is not a user, it is a machine with
 * one key, and a name of our own cannot be confused with a bearer token by
 * anything sitting in front of the Worker.
 *
 * [scripts/render-tape.mjs](../scripts/render-tape.mjs) sends it. That script is
 * plain Node and cannot import this constant, so it carries the same string with
 * a comment pointing here — and it fails on the first non-200 from the render
 * page rather than screenshotting 480 frames of a 404.
 */
export const RENDER_KEY_HEADER = "x-eventiq-render-key";

async function sha256(value: string): Promise<Uint8Array> {
  return new Uint8Array(await crypto.subtle.digest("SHA-256", encoder.encode(value)));
}

/**
 * Whether a presented secret is the expected one.
 *
 * Both sides are digested first and the digests compared, rather than comparing
 * the strings: `equal` returns early when two arrays are different lengths,
 * which is harmless for a signature of known size and is a length oracle for a
 * key somebody is guessing. Every comparison here is over 32 bytes.
 *
 * **A missing expectation matches nothing.** No default, no empty-string
 * shortcut, and the caller cannot pass one in by accident — otherwise the one
 * deployment that forgot to set the secret is the one open to everybody, and it
 * would look exactly like a working deployment until somebody probed it.
 */
export async function secretMatches(
  presented: string | null | undefined,
  expected: string | null | undefined,
): Promise<boolean> {
  if (!presented || !expected) return false;
  const [a, b] = await Promise.all([sha256(presented), sha256(expected)]);
  return equal(a, b);
}

async function hmacKey(secret: string): Promise<CryptoKey> {
  return crypto.subtle.importKey(
    "raw",
    encoder.encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign", "verify"],
  );
}

// ------------------------------------------------------------------ tokens

/**
 * An invite token. 32 bytes of randomness, which is the entire security of a
 * fighter's questionnaire, so it is generated from the CSPRNG and never from
 * anything derived from the fighter — a token built from a name and an event
 * would be guessable by anybody holding the printed card.
 */
export function newToken(): string {
  return toBase64Url(crypto.getRandomValues(new Uint8Array(32)));
}

/** Ids are opaque and only ever compared, so the same generator serves. */
export function newId(prefix: string): string {
  return `${prefix}_${toBase64Url(crypto.getRandomValues(new Uint8Array(12)))}`;
}

// ---------------------------------------------------------------- password

/**
 * `iterations:salt:hash`, all base64url. Stored rather than the password, so a
 * copy of the database is not a copy of the promoter's login.
 */
export async function hashPassword(password: string): Promise<string> {
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const hash = await derive(password, salt, PBKDF2_ITERATIONS);
  return `${PBKDF2_ITERATIONS}:${toBase64Url(salt)}:${toBase64Url(hash)}`;
}

async function derive(password: string, salt: Uint8Array, iterations: number): Promise<Uint8Array> {
  const key = await crypto.subtle.importKey("raw", encoder.encode(password), "PBKDF2", false, [
    "deriveBits",
  ]);
  const bits = await crypto.subtle.deriveBits(
    { name: "PBKDF2", salt: salt as BufferSource, iterations, hash: "SHA-256" },
    key,
    256,
  );
  return new Uint8Array(bits);
}

export async function verifyPassword(password: string, stored: string): Promise<boolean> {
  const [iterations, salt, hash] = stored.split(":");
  if (!iterations || !salt || !hash) return false;
  const candidate = await derive(password, fromBase64Url(salt), Number(iterations));
  return equal(candidate, fromBase64Url(hash));
}

// ---------------------------------------------------------------- sessions

export type Session = {
  promoterId: string;
  /** Unix seconds. Inside the signature, so the holder cannot extend it. */
  expiresAt: number;
};

export async function signSession(session: Session, secret: string): Promise<string> {
  const payload = toBase64Url(encoder.encode(JSON.stringify(session)));
  const key = await hmacKey(secret);
  const signature = await crypto.subtle.sign("HMAC", key, encoder.encode(payload));
  return `${payload}.${toBase64Url(new Uint8Array(signature))}`;
}

/**
 * Returns null for anything that is not a currently valid session, without
 * distinguishing between a forged signature and an expired one. The caller has
 * nothing useful to do with the difference and saying which is which tells an
 * attacker whether they have the secret right.
 */
export async function readSession(
  cookie: string | undefined,
  secret: string,
  now = Date.now(),
): Promise<Session | null> {
  if (!cookie) return null;
  const [payload, signature] = cookie.split(".");
  if (!payload || !signature) return null;

  let expected: Uint8Array;
  try {
    const key = await hmacKey(secret);
    expected = new Uint8Array(await crypto.subtle.sign("HMAC", key, encoder.encode(payload)));
    if (!equal(expected, fromBase64Url(signature))) return null;
  } catch {
    return null;
  }

  try {
    const session = JSON.parse(new TextDecoder().decode(fromBase64Url(payload))) as Session;
    if (typeof session.promoterId !== "string" || typeof session.expiresAt !== "number") return null;
    if (session.expiresAt * 1000 <= now) return null;
    return session;
  } catch {
    return null;
  }
}
