import type { Fighter } from "@/lib/types";

/**
 * What the sequence has to show where a fighter's face should be.
 *
 * Three states, in order of preference, and the order is the whole point of this
 * file. A cutout parallaxes against the backdrop and is what the sequence was
 * designed around. A photograph does not, but it is the fighter's actual face,
 * and a fighter who sent one and got an initialled plate anyway is the worst
 * outcome of the three: they did the thing they were asked to do and the video
 * says they ignored us. The plate is for the fighter who genuinely sent nothing,
 * which on an amateur card is most of the bill and is a state rather than a
 * fault.
 *
 * Cutouts are generated by the renderer rather than at upload — see
 * scripts/cutouts.mjs — so "photograph, no cutout yet" is the normal condition
 * of a fighter between submitting their form and the next render. It has to look
 * deliberate, not like a missing asset.
 */
export type Portrait =
  /** Background removed. Moves independently of the backdrop. */
  | { kind: "cutout"; src: string }
  /** The photograph as sent. Soft-masked and moved less, because it is a plane. */
  | { kind: "photo"; src: string }
  /** Nothing sent. The initialled plate. */
  | { kind: "plate" };

export function portraitOf(fighter: Pick<Fighter, "cutout" | "photo">): Portrait {
  if (fighter.cutout) return { kind: "cutout", src: fighter.cutout };
  if (fighter.photo) return { kind: "photo", src: fighter.photo };
  return { kind: "plate" };
}

/**
 * How far the subject travels against the backdrop, as a fraction of the full
 * cutout move.
 *
 * A cut-out subject can slide a long way over a drifting backdrop and read as
 * depth, because its edge is the fighter's own silhouette. A rectangle cannot:
 * the further it travels the more plainly it is a photograph being dragged
 * across a picture, and past a certain speed the eye stops seeing a fighter and
 * starts seeing a slide transition. So the photograph moves, because a still
 * frame in a moving sequence looks broken, but it moves about a third as far and
 * pushes in half as much.
 */
export const PARALLAX_TRAVEL: Record<Portrait["kind"], number> = {
  cutout: 1,
  photo: 0.34,
  plate: 1,
};

export function parallaxTravel(portrait: Portrait): number {
  return PARALLAX_TRAVEL[portrait.kind];
}

/**
 * Whether a cutout already on the profile is still a cutout of the photograph
 * that is on it.
 *
 * A cutout is derived from one particular photograph. Replace the photograph and
 * the stored cutout is a picture of something that is no longer on the card —
 * a previous haircut, a previous gym vest, or on a returning fighter a previous
 * person entirely if the promoter reassigned the row. So it is discarded and the
 * renderer cuts the new one out. Until it does, the video shows the photograph,
 * which is the fighter as they are now.
 */
export function cutoutSurvives(
  previousPhoto: string | null | undefined,
  nextPhoto: string | null | undefined,
): boolean {
  return (previousPhoto ?? null) === (nextPhoto ?? null);
}

/**
 * The initials on the plate. Two words at most, because three initials on a
 * 220px slab reads as an acronym rather than a person.
 */
export function plateInitials(name: string): string {
  return name
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part[0]?.toUpperCase() ?? "")
    .join("");
}
