import type { Fighter } from "@/lib/types";

/**
 * What the sequence has to show where a fighter's face should be.
 *
 * Three states, in order of preference, and the order is the whole point of this
 * file. A cutout parallaxes against the backdrop and is what the sequence was
 * designed around. A photograph does not, but it is the fighter's actual face,
 * and a fighter who sent one and got an initialled plate anyway is the worst
 * outcome of the three: they did the thing they were asked to do and the video
 * says they ignored us. The plate is for the fighter who genuinely sent nothing,
 * which on an amateur card is most of the bill and is a state rather than a
 * fault.
 *
 * Cutouts are generated by the renderer rather than at upload — see
 * scripts/cutouts.mjs — so "photograph, no cutout yet" is the normal condition
 * of a fighter between submitting their form and the next render. It has to look
 * deliberate, not like a missing asset.
 */
export type Portrait =
  /**
   * Poster art the fighter asked for and then approved. First, and only ever
   * reachable through a stored column that nothing but an approval writes.
   */
  | { kind: "stylised"; src: string }
  /** Background removed. Moves independently of the backdrop. */
  | { kind: "cutout"; src: string }
  /** The photograph as sent. Soft-masked and moved less, because it is a plane. */
  | { kind: "photo"; src: string }
  /** Nothing sent. The initialled plate. */
  | { kind: "plate" };

/**
 * The stylised portrait goes above the cutout, and the reason is consent rather
 * than picture quality.
 *
 * A cutout is something we made from a fighter's photograph without asking. A
 * stylised portrait is something they opted into, waited for, looked at and
 * pressed approve on, and it is the only one of the four that answers a question
 * they were actually asked. Ranking it below the cutout would mean the fighter
 * approving an image and then not seeing it, which is worse than any of the
 * treatments looking better than another.
 *
 * It cannot displace a real photograph by accident, because it is null until an
 * approval writes it and it is cleared whenever the photograph it was made from
 * is replaced — the same rule the cutout is held to. Generated art is never what
 * a fighter gets for sending a picture and saying nothing.
 */
export function portraitOf(fighter: Pick<Fighter, "cutout" | "photo" | "stylised">): Portrait {
  if (fighter.stylised) return { kind: "stylised", src: fighter.stylised };
  if (fighter.cutout) return { kind: "cutout", src: fighter.cutout };
  if (fighter.photo) return { kind: "photo", src: fighter.photo };
  return { kind: "plate" };
}

/**
 * How far the subject travels against the backdrop, as a fraction of the full
 * cutout move.
 *
 * A cut-out subject can slide a long way over a drifting backdrop and read as
 * depth, because its edge is the fighter's own silhouette. A rectangle cannot:
 * the further it travels the more plainly it is a photograph being dragged
 * across a picture, and past a certain speed the eye stops seeing a fighter and
 * starts seeing a slide transition. So the photograph moves, because a still
 * frame in a moving sequence looks broken, but it moves about a third as far and
 * pushes in half as much.
 */
export const PARALLAX_TRAVEL: Record<Portrait["kind"], number> = {
  cutout: 1,
  photo: 0.34,
  // Poster art comes back as a rectangle with a background of its own, so it is
  // a plane in the frame exactly as a photograph is and travels the same way.
  stylised: 0.34,
  plate: 1,
};

export function parallaxTravel(portrait: Portrait): number {
  return PARALLAX_TRAVEL[portrait.kind];
}

/**
 * Whether a cutout already on the profile is still a cutout of the photograph
 * that is on it.
 *
 * A cutout is derived from one particular photograph. Replace the photograph and
 * the stored cutout is a picture of something that is no longer on the card —
 * a previous haircut, a previous gym vest, or on a returning fighter a previous
 * person entirely if the promoter reassigned the row. So it is discarded and the
 * renderer cuts the new one out. Until it does, the video shows the photograph,
 * which is the fighter as they are now.
 */
export function cutoutSurvives(
  previousPhoto: string | null | undefined,
  nextPhoto: string | null | undefined,
): boolean {
  return (previousPhoto ?? null) === (nextPhoto ?? null);
}

/**
 * The bucket key behind a stored portrait path, or null for anything else.
 *
 * Only `/media/...` is ours to delete. The seeded card's photographs are static
 * assets committed under public/, and an absolute URL or a blob: from a preview
 * is not an object at all, so both come back null and nothing is deleted for
 * them. The same character rule as parseMediaKey, so a path this accepts is a
 * path that route would have served.
 */
export function mediaKeyOf(path: string | null | undefined): string | null {
  if (!path || !path.startsWith("/media/")) return null;
  const key = path.slice("/media/".length);
  if (!/^[A-Za-z0-9][A-Za-z0-9._/-]*$/.test(key) || key.includes("..")) return null;
  return key;
}

/** Where a stylised portrait lives. Its own prefix, so /media can have a rule for it. */
export const STYLISED_PREFIX = "portraits";

/** The key for one, with the random suffix that stops a replacement being cached. */
export function stylisedKey(fighterId: string, suffix: string, extension: string): string {
  return `${STYLISED_PREFIX}/${fighterId}-${suffix}.${extension}`;
}

/**
 * Whether a path names a stylised portrait of this fighter.
 *
 * The approve action takes the path back from the browser, so it has to be
 * checked rather than believed: without this, a fighter holding one invite could
 * approve any object in the prefix onto their own card, including one drawn from
 * somebody else's photograph. Fighter ids are hyphenated, so the id is matched
 * as a prefix and the remainder has to be the suffix and extension this file
 * writes rather than anything else containing a hyphen.
 */
export function stylisedBelongsTo(path: string, fighterId: string): boolean {
  const key = mediaKeyOf(path);
  if (!key || !key.startsWith(`${STYLISED_PREFIX}/`)) return false;
  const name = key.slice(STYLISED_PREFIX.length + 1);
  if (!name.startsWith(`${fighterId}-`)) return false;
  return /^[A-Za-z0-9]{4,32}\.[a-z]{3,4}$/.test(name.slice(fighterId.length + 1));
}

/**
 * The initials on the plate. Two words at most, because three initials on a
 * 220px slab reads as an acronym rather than a person.
 */
export function plateInitials(name: string): string {
  return name
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part[0]?.toUpperCase() ?? "")
    .join("");
}
